; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-2432s028

[env:esp32-2432s028]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
	bodmer/TFT_eSPI@^2.5.0
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	arduino-libraries/NTPClient@^3.2.1
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DENABLE_TFT_DISPLAY
	-I${PROJECT_SRC_DIR}
extra_scripts = 
	pre:copy_user_setup.py
monitor_speed = 115200

[env:esp32-ili9341-38pin]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
	bodmer/TFT_eSPI@^2.5.0
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	arduino-libraries/NTPClient@^3.2.1
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DENABLE_TFT_DISPLAY
	-DTOUCH_IRQ=35
	-DTOUCH_MISO=27
	-I${PROJECT_SRC_DIR}
extra_scripts = 
	pre:copy_user_setup.py
monitor_speed = 115200
